### PR TITLE
Avoid clash with id generated by org-html-toc

### PR DESCRIPTION
**Pull request by steelman**

### CODE REVIEW

**Comment by yjwen** [comment]
I saw it is a change of the TOC section's id. But I am not very conscious about the purpose. Could you please give me a description why it is necessary?

**Comment by steelman** [comment]
According to paragraph 3.2.6 of HTML spec[1]

> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace.


[1] https://html.spec.whatwg.org/

**Comment by yjwen** [comment]
I see. It conflicts with the `<div id="table-of-contents">` done by ox-html.

**Comment by yjwen** [comment]
Thanks for the correction.

**Pull request merged**
