### PR TITLE
Add Badges

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Add badges for melpa, melpa stable, tags, and licence.

(and delete execution right to files)

### CODE REVIEW

**Comment by yjwen** [comment]
erh...what is a badge for?

**Comment by AdrieanKhisbe** [comment]
The goal is that one can  see on a glance on github which are the latest melpa version avilable, 
and can compare to the tag version of the repo.

ex: https://github.com/dpsutton/resize-window

**Comment by yjwen** [comment]
I see. Thanks!

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Comment by AdrieanKhisbe** [comment]
ffffff*****, I used markdown syntax.

**Comment by AdrieanKhisbe** [comment]
Fixed it in #176, sorry again for this

**Pull request merged**
