### PR TITLE
Enable stable numbering scheme for slides

### PR DESCRIPTION
**Pull request by phillord**
Addresses #262

### CODE REVIEW

**Comment by jgkamat** [comment]
I would love this to get merged! @yjwen?

**Comment by kellpossible** [comment]
thanks, this seems to work well

**Comment by nickjmeyer** [comment]
Just gave this a try.  Looks to not number in the correct order.

If I have just a horizontal slide layout, then its fine.  If there are vertical slides, then the vertical slides are numbers before the to most slide.  For example, if I have the following slide layout
```
h1.s1    h2.s1    h3.s1
         h2.s2
```
Then the slide numbers are `h1.s1 = 1`, `h2.s1 = 3`, `h2.s2 = 2`, `h3.s1 = 4`.  It would make more sense for it to be `h1.s1 = 1`, `h2.s1 = 2`, `h2.s2 = 3`, `h3.s1 = 4`.

**Comment by phillord** [comment]
@nickjmeyer This would be fixable, but want to know whether @yjwen is interested in the patch at all.

**Comment by AdrieanKhisbe** [comment]
(Little poke being also interested in this PR getting merged)
cc @yjwen

**Comment by AdrieanKhisbe** [comment]
After some digging I think it would be ore sense not to have a number but a tuple: (horizontal, vertical) ex `1/2`.
This is the exact same numbering we have on the bottom right corner (1-2)
cf http://lab.hakim.se/reveal-js/#/2/2

**Comment by nickjmeyer** [comment]
Agreed. That would make a lot more sense.

**Comment by joonro** [comment]
This looks great! I agree x/x numbering which would be identical to the number on the lower right (x/x format) would be ideal. I hope @yjwen will have a chance to take a look at this soon.

**Comment by yjwen** [comment]
orgmode has updated with consistent section numbering. And org-reveal has just been updated to utilize orgmode's numbering by https://github.com/yjwen/org-reveal/commit/6052357f26d8e8fff09da17bd6f998ab71c41b64 .

Thanks for the great effort of @phillord and all the others. I am going to close this merge request.

**Comment by joonro** [comment]
That is a great news!

**Comment by nikclayton** [comment]
Just in case anyone else bumps in to this:

This doesn't work if you use

```
#+OPTIONS: num:nil
```

to disable heading numbers appearing in slides -- it falls back to generating non-repeatable UUIDs as section numbers, which aren't stable across subsequent reloads.

Since I don't want the section numbers being visible on the slides I modified the custom CSS and added

```
span[class|=section-number] {
  display: none;
}
```

**Pull request closed without merging**
